---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by rosenth.
--- DateTime: 10.07.21 22:53
---

function send_error(msg)
    server.print(msg)
    server.log(msg, server.loglevel.LOG_ERR)
    server.sendStatus(500)
    return false
end

local success, cwd = server.fs.getcwd()
if not success then
    return send_error(cwd)
end

local success, ftype1 = server.fs.ftype('/dev/null')
if not success then
    return send_error(ftype1)
end

local success, ftype2 = server.fs.ftype('./testserver')
if not success then
    return send_error(ftype2)
end

local success, modtime = server.fs.modtime('./test_00.cpp')
if not success then
    return send_error(modtime)
end

local success, dirlist = server.fs.readdir('./testserver')
if not success then
    return send_error(dirlist)
end


result = {
    status = 'OK',
    fs = {
        cwd = cwd,
        ftype1 = ftype1,
        ftype2 = ftype2,
        modtime = modtime,
        dirlist = dirlist
    }
}

local success, jsonresult = server.table_to_json(result)
if not success then
    return send_error(jsonresult)
end

server.sendHeader('Content-type', 'application/json')
server.sendStatus(200)
server.print(jsonresult)
return true
