---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by rosenth.
--- DateTime: 11.07.21 16:17
---
function send_error(msg)
    server.print(msg)
    server.log(msg, server.loglevel.LOG_ERR)
    server.sendStatus(500)
    return false
end

-- always success by design :-)
local success, uuid = server.uuid()

-- always success by design :-)
local success, uuid62 = server.uuid62()

local success, uuid62_2 = server.uuid_to_base62(uuid)
if not success then
    send_error(uuid62_2)
end

success, uuid_2 = server.base62_to_uuid(uuid62)
if not success then
    send_error(uuid_2)
end

local jwt = '!!!! NO JWT!!!!!'
if server.has_openssl then
    jwtinfo = {
        iss = 'http://cserver.org',
        aud = 'http://test.org',
        prn = 'https://test.org/gaga',
        jti = '1234567890',
        key = 'abcdefghijk'
    }
    success, jwt = server.generate_jwt(jwtinfo)
end

local success, token = server.decode_jwt(server.get.jwt)
if not success then
    send_error(token)
end

result = {
    status = 'OK',
    uuid = uuid,
    uuid62 = uuid62,
    uuid62_2 = uuid62_2,
    uuid_2 = uuid_2,
    jwt = jwt,
    token = token
}

local success, jsonresult = server.table_to_json(result)
if not success then
    server.log("server.table_to_json failed: " .. errmsg, server.loglevel.LOG_ERR)
    server.sendStatus(500)
    print.print("server.table_to_json failed: " .. errmsg)
    return false
end
server.sendHeader('Content-type', 'application/json')
server.sendStatus(200)
server.print(jsonresult)
return true
