---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by rosenth.
--- DateTime: 26.07.21 14:02
---
require "send_response"

function test_db()
    local db = sqlite("./testdata/testdb.sqlite3", "RW")
    local qry = db << "SELECT * FROM test WHERE uuid = ?1 OR uuid = ?2 ORDER BY uuid"
    local id = "46c21d94-77b3-485f-9089-c40023738ce5"
    local result = {}
    local row = qry(id, "1c1dcc9d-8e80-43a6-8421-56c5b5f42de7")
    while row do
        result[row[0]] = row[1]
        row = qry()
    end
    qry = ~qry
    db = ~db
    return result
end


local status, res = pcall(test_db)
if not status then
    local resobj = {
        status = 'ERROR',
        result = res
    }
    send_error(500, resobj)
    return false
else
    local resobj = {
        status = 'OK',
        result = res
    }
    send_success(resobj)
end

